SET SERVEOUTPUT ON 

DECLARE  
    PI  CONSTANT NUMBER := 3.14;
BEGIN  
    DBMS_OUTPUT.PUT_LINE('O valor de PI é: ' || PI);
END;

DECLARE
  ESTADO CONSTANT CHAR(20) := 'Rio De Janeiro';
  COMPLEMENTO CONSTANT CHAR(30) := 'Niterói, Ponta Da Areia';
BEGIN
  DBMS_OUTPUT.PUT_LINE(ESTADO || COMPLEMENTO);
END;
